"""Static measure-point data transcribed from the iSolarCloud docs.

Source: mcp-isolarcloud docs server (``common-*-measuring-points`` pages).
No logic here — see ``measure_points.py``.
"""

from __future__ import annotations

from .modbus_registers import MODBUS_ENUM_MAPS

# --- Enum value tables (point_id -> {int_code: label}) ------------------------

_CHARGER_STATUS: dict[int, str] = {
    1: "Idle (not plugged in)",
    2: "Standby (plugged in)",
    3: "Charging",
    4: "Charging paused (station)",
    5: "Charging paused (vehicle)",
    6: "Charging completed",
    7: "Reserved",
    8: "Disabled",
    9: "Fault",
}

# Inverter operating status (point 29) and energy-storage-inverter operating
# status (point 13146) share this documented family.
_OPERATING_STATUS: dict[int, str] = {
    0: "Grid-connected operation",
    20: "Microgrid operation",
    64: "Grid-connected, operating normally",
    65: "Off-grid charging",
    128: "Derated running",
    256: "Operation fault",
    512: "Update failed",
    1024: "Maintenance mode",
    2048: "Forced mode",
    4096: "Off-grid",
    4369: "Uninitialized",
    4608: "Initial standby",
    4864: "Awaiting startup",
    5120: "Standby",
    5376: "Emergency stop",
    5632: "Starting up",
    5888: "AFCI self-test",
    6144: "Smart plant building status",
    6400: "Security mode",
    8192: "Open loop",
    9472: "LCD/DSP communication fault",
    9473: "Restarting",
    16384: "Energy dispatch mode",
    16385: "Emergency charging mode",
    16435: "Low insulation resistance",
    16439: "Insulation board anomaly",
    20992: "Shutting down",
    21760: "Shut down due to faults",
    32768: "Shut down",
    33024: "Derated running",
    33280: "Dispatched running",
    33792: "Running under anti-PID condition",
    37120: "Running with alarm",
}

_MICROINVERTER_STATUS: dict[int, str] = {
    0: "On-grid operation",
    1024: "Maintenance mode",
    2048: "Forced mode",
    4096: "Backup operation",
    4369: "Initial status",
    4608: "Initial standby",
    4864: "Press to shut down",
    5120: "Standby",
    5632: "Starting up",
    8192: "Open loop",
    21760: "Shut down due to faults",
    32768: "Shutdown",
    33024: "Derating running",
    33280: "Dispatch running",
    37120: "Warn run",
}

ENUM_MAPS: dict[str, dict[int, str]] = {
    "33716": _CHARGER_STATUS,
    "29": _OPERATING_STATUS,
    "13146": _OPERATING_STATUS,
    "51301": _MICROINVERTER_STATUS,
    # Local-Modbus point-code enum tables (running_state_raw, device_type_code)
    # merged in from ``modbus_registers`` so the existing enum sensor pipeline
    # (options, resolve_enum_value) handles cloud and Modbus points uniformly (#322).
    **MODBUS_ENUM_MAPS,
}

# --- Catalog rows: (point_id, english_name, unit). Blank unit = "". -----------
# Transcribed verbatim from the mcp-isolarcloud measuring-point catalogs; doc
# superscripts normalised (e.g. "W/m^2^" -> "W/m²"). CMU/BSC share IDs
# 59008/59010/59012/59014 (same cell voltage/temperature points) — listed once.
RAW_POINTS: list[tuple[str, str, str]] = [
    # --- Battery (common-battery-measuring-points) ---
    ("58601", "Battery Voltage", "V"),
    ("58602", "Battery Current", "A"),
    ("58603", "Battery Temperature", "°C"),
    ("58604", "Battery Level", ""),
    ("58605", "Battery Health (SOH)", ""),
    ("58606", "Total Battery Charging Energy", "Wh"),
    ("58607", "Total Battery Discharging Energy", "Wh"),
    ("58608", "Battery Operation Status", ""),
    ("58609", "Standard Health Status", ""),
    ("58610", "Max. Voltage of Cell", "mV"),
    ("58611", "Position of Max-Voltage Cell", ""),
    ("58612", "Min. Voltage of Cell", "mV"),
    ("58613", "Position of Min-Voltage Cell", ""),
    ("58614", "Max. Temperature of Module", "°C"),
    ("58615", "Max. Temperature Position of Module", ""),
    ("58616", "Min. Temperature of Module", "°C"),
    ("58617", "Min. Temperature Position of Module", ""),
    ("58618", "Max. Cell Voltage of Module 1", "mV"),
    ("58619", "Max. Cell Voltage of Module 2", "mV"),
    ("58620", "Max. Cell Voltage of Module 3", "mV"),
    ("58621", "Max. Cell Voltage of Module 4", "mV"),
    ("58622", "Max. Cell Voltage of Module 5", "mV"),
    ("58623", "Max. Cell Voltage of Module 6", "mV"),
    ("58624", "Max. Cell Voltage of Module 7", "mV"),
    ("58625", "Max. Cell Voltage of Module 8", "mV"),
    ("58626", "Min. Cell Voltage of Module 1", "mV"),
    ("58627", "Min. Cell Voltage of Module 2", "mV"),
    ("58628", "Min. Cell Voltage of Module 3", "mV"),
    ("58629", "Min. Cell Voltage of Module 4", "mV"),
    ("58630", "Min. Cell Voltage of Module 5", "mV"),
    ("58631", "Min. Cell Voltage of Module 6", "mV"),
    ("58632", "Min. Cell Voltage of Module 7", "mV"),
    ("58633", "Min. Cell Voltage of Module 8", "mV"),
    ("58635", "DC Contactor Status", ""),
    ("58636", "Fault Module ID", ""),
    # --- EV charger (common-charger-measuring-points) ---
    ("33708", "Charging Power", "kW"),
    ("33722", "Min. Charge Power", "kW"),
    ("33723", "Max. Charging Power", "kW"),
    ("33702", "Phase A Charging Voltage", "V"),
    ("33704", "Phase B Charging Voltage", "V"),
    ("33706", "Phase C Charging Voltage", "V"),
    ("33710", "CP Voltage", "V"),
    ("33703", "Phase A Charging Current", "A"),
    ("33705", "Phase B Charging Current", "A"),
    ("33707", "Phase C Charging Current", "A"),
    ("33728", "Max. Charging Current", "A"),
    ("33729", "Min. Charge Current", "A"),
    ("33716", "Charging Status", ""),
    # --- Energy meter (common-energy-meter-measuring-points) ---
    ("8030", "Forward Active Energy", "Wh"),
    ("8031", "Reverse Active Energy", "Wh"),
    ("8062", "Daily Forward Active Energy", "Wh"),
    ("8063", "Daily Reverse Active Energy", "Wh"),
    ("8032", "Forward Reactive Energy", "varh"),
    ("8033", "Reverse Reactive Energy", "varh"),
    ("8034", "Peak Forward Active Energy", "Wh"),
    ("8035", "Peak Reverse Active Energy", "Wh"),
    ("8038", "Valley Forward Active Energy", "Wh"),
    ("8039", "Valley Reverse Active Energy", "Wh"),
    ("8042", "Flat Forward Active Energy", "Wh"),
    ("8043", "Flat Reverse Active Energy", "Wh"),
    ("8058", "Wave Forward Active Energy", "Wh"),
    ("8059", "Wave Reverse Active Energy", "Wh"),
    ("8036", "Peak Forward Reactive Energy", "Wh"),
    ("8037", "Peak Reverse Reactive Energy", "Wh"),
    ("8040", "Valley Forward Reactive Energy", "Wh"),
    ("8041", "Valley Reverse Reactive Energy", "Wh"),
    ("8044", "Flat Forward Reactive Energy", "Wh"),
    ("8045", "Flat Reverse Reactive Energy", "Wh"),
    ("8060", "Wave Forward Reactive Energy", "Wh"),
    ("8061", "Wave Reverse Reactive Energy", "Wh"),
    ("8000", "Phase A Voltage", "V"),
    ("8001", "Phase B Voltage", "V"),
    ("8002", "Phase C Voltage", "V"),
    ("8003", "A-B Line Voltage", "V"),
    ("8004", "B-C Line Voltage", "V"),
    ("8005", "C-A Line Voltage", "V"),
    ("8006", "Phase A Current", "A"),
    ("8007", "Phase B Current", "A"),
    ("8008", "Phase C Current", "A"),
    ("8064", "Frequency", "Hz"),
    ("8018", "Meter Active Power", "W"),
    ("8022", "Reactive Power", "var"),
    ("8014", "Power Factor", ""),
    ("8026", "Apparent Power", "VA"),
    ("8076", "Meter Phase A Active Power", "W"),
    ("8077", "Meter Phase B Active Power", "W"),
    ("8078", "Meter Phase C Active Power", "W"),
    ("8084", "Daily Direct Power Consumption", "Wh"),
    ("8085", "Total Direct Power Consumption", "Wh"),
    # --- EMS device (common-ems-device-measuring-points) ---
    ("24620", "ESS Daily Charge", "Wh"),
    ("24621", "ESS Daily Discharge", "Wh"),
    ("24622", "ESS Total Charge", "Wh"),
    ("24623", "ESS Total Discharge", "Wh"),
    ("24624", "PV Active Power", "W"),
    ("24625", "Energy Storage Active Power", "W"),
    ("24626", "Grid Active Power", "W"),
    ("24627", "Daily PV Yield", "Wh"),
    ("24628", "Total PV Yield", "Wh"),
    ("24629", "Energy Storage SOC", "%"),
    ("24630", "Energy Storage Remaining Charge", "Wh"),
    ("24631", "Active Load", "W"),
    # --- Energy storage inverter (common-energy-storage-inverter-measuring-points) ---
    ("13011", "Active Power", "W"),
    ("13003", "Total DC Power", "W"),
    ("13157", "Phase A Voltage", "V"),
    ("13158", "Phase B Voltage", "V"),
    ("13159", "Phase C Voltage", "V"),
    ("13008", "Phase A Current", "A"),
    ("13009", "Phase B Current", "A"),
    ("13010", "Phase C Current", "A"),
    ("13012", "Total Reactive Power", "var"),
    ("13160", "Array Insulation Resistance", "kΩ"),
    ("13007", "Grid Frequency", "Hz"),
    ("18065", "Phase A Backup Power", "W"),
    ("18066", "Phase B Backup Power", "W"),
    ("18067", "Phase C Backup Power", "W"),
    ("18068", "Total Backup Power", "W"),
    ("18062", "Phase A Backup Current", "A"),
    ("18063", "Phase B Backup Current", "A"),
    ("18064", "Phase C Backup Current", "A"),
    ("13020", "Total Operation Time", "h"),
    ("13134", "Total PV Yield", "Wh"),
    ("13112", "Daily PV Yield", "Wh"),
    ("13187", "AC Voltage", "V"),
    ("13188", "AC Current", "A"),
    ("13004", "A-B Line Voltage", "V"),
    ("13005", "B-C Line Voltage", "V"),
    ("13006", "C-A Line Voltage", "V"),
    ("13019", "Internal Air Temperature", "°C"),
    ("13161", "Bus Voltage", "V"),
    ("13013", "Total Power Factor", ""),
    ("13001", "MPPT1 Voltage", "V"),
    ("13002", "MPPT1 Current", "A"),
    ("13105", "MPPT2 Voltage", "V"),
    ("13106", "MPPT2 Current", "A"),
    ("13107", "MPPT3 Voltage", "V"),
    ("13108", "MPPT3 Current", "A"),
    ("13109", "MPPT4 Voltage", "V"),
    ("13110", "MPPT4 Current", "A"),
    ("13122", "Feed-in Energy Today", "Wh"),
    ("13125", "Total Feed-in Energy", "Wh"),
    ("13147", "Energy Purchased Today", "Wh"),
    ("13148", "Total Purchased Energy", "Wh"),
    ("13149", "Purchased Power", "W"),
    ("13121", "Feed-in Power", "W"),
    ("13173", "Feed-in Energy Today (PV)", "Wh"),
    ("13175", "Total Feed-in Energy (PV)", "Wh"),
    ("13141", "Battery Level (SOC)", ""),
    ("13029", "Battery Discharging Energy Today", "Wh"),
    ("13028", "Battery Charging Energy Today", "Wh"),
    ("13138", "Battery Voltage", "V"),
    ("13139", "Battery Current", "A"),
    ("13035", "Total Battery Discharging Energy", "Wh"),
    ("13034", "Total Battery Charging Energy", "Wh"),
    ("13142", "Battery Health (SOH)", ""),
    ("13143", "Battery Temperature", "°C"),
    ("13162", "Max. Charging Current (BMS)", "A"),
    ("13163", "Max. Discharging Current (BMS)", "A"),
    ("13174", "Daily Battery Charging Energy from PV", "Wh"),
    ("13176", "Total Battery Charging Energy from PV", "Wh"),
    ("13126", "Battery Charging Power", "W"),
    ("13150", "Battery Discharging Power", "W"),
    ("13199", "Daily Load Consumption", "Wh"),
    ("13137", "Total Load Energy Consumption from PV", "Wh"),
    ("13119", "Load Power", "W"),
    ("13130", "Total Load Consumption", "Wh"),
    ("13116", "Daily Direct Energy Consumption", "Wh"),
    ("13144", "Daily Self-consumption Rate", ""),
    ("13016", "Total Charging Time", "h"),
    ("13017", "Total Discharging Time", "h"),
    ("13018", "Total Apparent Power", "VA"),
    ("13023", "Daily Charging Time", "h"),
    ("13024", "Daily Discharging Time", "h"),
    ("13118", "Annual Direct Energy Consumption", "Wh"),
    ("13165", "MDSP Off-Grid Start Up Status", ""),
    ("13166", "SDSP Working Mode", ""),
    ("13167", "SDSP Off-grid Start Status", ""),
    ("13168", "DI Status", ""),
    ("13169", "Battery Voltage (BMS)", "V"),
    ("13170", "Battery SOC (BMS)", ""),
    ("13171", "EMS Status", ""),
    ("13172", "Daily Self-Sufficiency Rate", ""),
    ("13140", "Battery Capacity", "Wh"),
    ("18075", "Channel 2 Total Apparent Power", "VA"),
    ("18076", "Channel 2 Phase A Apparent Power", "VA"),
    ("18077", "Channel 2 Phase B Apparent Power", "VA"),
    ("18078", "Channel 2 Phase C Apparent Power", "VA"),
    ("18079", "Channel 2 Total Active Power", "W"),
    ("18080", "Channel 2 Phase A Active Power", "W"),
    ("18081", "Channel 2 Phase B Active Power", "W"),
    ("18082", "Channel 2 Phase C Active Power", "W"),
    ("18083", "Channel 2 Total Reactive Power", "var"),
    ("18084", "Channel 2 Phase A Reactive Power", "var"),
    ("18085", "Channel 2 Phase B Reactive Power", "var"),
    ("18086", "Channel 2 Phase C Reactive Power", "var"),
    ("18087", "Channel 2 Power Factor", ""),
    ("18088", "Channel 2 Total Purchased Energy", "Wh"),
    ("18089", "Channel 2 Phase A Purchased Energy", "Wh"),
    ("18090", "Channel 2 Phase B Purchased Energy", "Wh"),
    ("18091", "Channel 2 Phase C Purchased Energy", "Wh"),
    ("18092", "Channel 2 Total Feed-in Energy", "Wh"),
    ("18093", "Channel 2 Phase A Feed-in Energy", "Wh"),
    ("18094", "Channel 2 Phase B Feed-in Energy", "Wh"),
    ("18095", "Channel 2 Phase C Feed-in Energy", "Wh"),
    ("18103", "Phase A Backup Voltage", "V"),
    ("18104", "Phase B Backup Voltage", "V"),
    ("18105", "Phase C Backup Voltage", "V"),
    ("18108", "Meter Phase-A Voltage", "V"),
    ("18109", "Meter Phase-B Voltage", "V"),
    ("18110", "Meter Phase-C Voltage", "V"),
    ("13146", "Operating Status", ""),
    # --- String inverter (common-inverter-measuring-points) ---
    ("1", "Yield Today", "Wh"),
    ("87", "Yield This Month", "Wh"),
    ("88", "Yield This Year", "Wh"),
    ("2", "Total Yield", "Wh"),
    ("24", "Total Active Power", "W"),
    ("14", "Total DC Power", "W"),
    ("18", "Phase A Voltage", "V"),
    ("19", "Phase B Voltage", "V"),
    ("20", "Phase C Voltage", "V"),
    ("21", "Phase A Current", "A"),
    ("22", "Phase B Current", "A"),
    ("23", "Phase C Current", "A"),
    ("25", "Total Reactive Power", "var"),
    ("94", "Array Insulation Resistance", "kΩ"),
    ("27", "Grid Frequency", "Hz"),
    ("7356", "Total Operation Time", "h"),
    ("15", "A-B Line Voltage", "V"),
    ("16", "B-C Line Voltage", "V"),
    ("17", "C-A Line Voltage", "V"),
    ("4", "Internal Air Temperature", "°C"),
    ("95", "Bus Voltage", "V"),
    ("26", "Total Power Factor", ""),
    ("120", "Number of AFCI Faults", ""),
    ("90", "Negative Voltage to Ground", "V"),
    ("43", "Total Apparent Power", "VA"),
    ("33", "Module 1 Temperature", "°C"),
    ("34", "Module 2 Temperature", "°C"),
    ("35", "Module 3 Temperature", "°C"),
    ("36", "Module 4 Temperature", "°C"),
    ("37", "Module 5 Temperature", "°C"),
    ("38", "Module 6 Temperature", "°C"),
    ("39", "Positive Impedance to Ground", "Ω"),
    ("40", "Negative Impedance to Ground", "Ω"),
    ("41", "Active Power Regulation Actual Value", "W"),
    ("42", "Reactive Power Regulation Actual Value", "var"),
    ("67", "Daily Yield (Theoretical)", "Wh"),
    ("5", "MPPT1 Voltage", "V"),
    ("6", "MPPT1 Current", "A"),
    ("7", "MPPT2 Voltage", "V"),
    ("8", "MPPT2 Current", "A"),
    ("9", "MPPT3 Voltage", "V"),
    ("10", "MPPT3 Current", "A"),
    ("45", "MPPT4 Voltage", "V"),
    ("46", "MPPT4 Current", "A"),
    ("47", "MPPT5 Voltage", "V"),
    ("48", "MPPT5 Current", "A"),
    ("49", "MPPT6 Voltage", "V"),
    ("50", "MPPT6 Current", "A"),
    ("51", "MPPT7 Voltage", "V"),
    ("52", "MPPT7 Current", "A"),
    ("53", "MPPT8 Voltage", "V"),
    ("54", "MPPT8 Current", "A"),
    ("55", "MPPT9 Voltage", "V"),
    ("56", "MPPT9 Current", "A"),
    ("57", "MPPT10 Voltage", "V"),
    ("58", "MPPT10 Current", "A"),
    ("7401", "MPPT11 Voltage", "V"),
    ("7451", "MPPT11 Current", "A"),
    ("7402", "MPPT12 Voltage", "V"),
    ("7452", "MPPT12 Current", "A"),
    ("7723", "MPPT13 Voltage", "V"),
    ("7724", "MPPT13 Current", "A"),
    ("7725", "MPPT14 Voltage", "V"),
    ("7726", "MPPT14 Current", "A"),
    ("7727", "MPPT15 Voltage", "V"),
    ("7728", "MPPT15 Current", "A"),
    ("7729", "MPPT16 Voltage", "V"),
    ("7730", "MPPT16 Current", "A"),
    ("7731", "MPPT17 Voltage", "V"),
    ("7732", "MPPT17 Current", "A"),
    ("7733", "MPPT18 Voltage", "V"),
    ("7734", "MPPT18 Current", "A"),
    ("7735", "MPPT19 Voltage", "V"),
    ("7736", "MPPT19 Current", "A"),
    ("7737", "MPPT20 Voltage", "V"),
    ("7738", "MPPT20 Current", "A"),
    ("96", "String 1 Voltage", "V"),
    ("70", "String 1 Current", "A"),
    ("97", "String 2 Voltage", "V"),
    ("71", "String 2 Current", "A"),
    ("98", "String 3 Voltage", "V"),
    ("72", "String 3 Current", "A"),
    ("99", "String 4 Voltage", "V"),
    ("73", "String 4 Current", "A"),
    ("100", "String 5 Voltage", "V"),
    ("74", "String 5 Current", "A"),
    ("101", "String 6 Voltage", "V"),
    ("75", "String 6 Current", "A"),
    ("102", "String 7 Voltage", "V"),
    ("76", "String 7 Current", "A"),
    ("103", "String 8 Voltage", "V"),
    ("77", "String 8 Current", "A"),
    ("104", "String 9 Voltage", "V"),
    ("78", "String 9 Current", "A"),
    ("105", "String 10 Voltage", "V"),
    ("79", "String 10 Current", "A"),
    ("106", "String 11 Voltage", "V"),
    ("80", "String 11 Current", "A"),
    ("107", "String 12 Voltage", "V"),
    ("81", "String 12 Current", "A"),
    ("108", "String 13 Voltage", "V"),
    ("82", "String 13 Current", "A"),
    ("109", "String 14 Voltage", "V"),
    ("83", "String 14 Current", "A"),
    ("110", "String 15 Voltage", "V"),
    ("84", "String 15 Current", "A"),
    ("111", "String 16 Voltage", "V"),
    ("85", "String 16 Current", "A"),
    ("112", "String 17 Voltage", "V"),
    ("92", "String 17 Current", "A"),
    ("113", "String 18 Voltage", "V"),
    ("93", "String 18 Current", "A"),
    ("7166", "String 19 Voltage", "V"),
    ("313", "String 19 Current", "A"),
    ("7167", "String 20 Voltage", "V"),
    ("314", "String 20 Current", "A"),
    ("7168", "String 21 Voltage", "V"),
    ("315", "String 21 Current", "A"),
    ("7169", "String 22 Voltage", "V"),
    ("316", "String 22 Current", "A"),
    ("7170", "String 23 Voltage", "V"),
    ("317", "String 23 Current", "A"),
    ("7171", "String 24 Voltage", "V"),
    ("318", "String 24 Current", "A"),
    ("7172", "String 25 Voltage", "V"),
    ("319", "String 25 Current", "A"),
    ("7173", "String 26 Voltage", "V"),
    ("320", "String 26 Current", "A"),
    ("7174", "String 27 Voltage", "V"),
    ("321", "String 27 Current", "A"),
    ("7175", "String 28 Voltage", "V"),
    ("322", "String 28 Current", "A"),
    ("7176", "String 29 Voltage", "V"),
    ("323", "String 29 Current", "A"),
    ("7177", "String 30 Voltage", "V"),
    ("324", "String 30 Current", "A"),
    ("7178", "String 31 Voltage", "V"),
    ("325", "String 31 Current", "A"),
    ("7179", "String 32 Voltage", "V"),
    ("326", "String 32 Current", "A"),
    ("7707", "String 33 Voltage", "V"),
    ("7708", "String 33 Current", "A"),
    ("7709", "String 34 Voltage", "V"),
    ("7710", "String 34 Current", "A"),
    ("7711", "String 35 Voltage", "V"),
    ("7712", "String 35 Current", "A"),
    ("7713", "String 36 Voltage", "V"),
    ("7714", "String 36 Current", "A"),
    ("7715", "String 37 Voltage", "V"),
    ("7716", "String 37 Current", "A"),
    ("7717", "String 38 Voltage", "V"),
    ("7718", "String 38 Current", "A"),
    ("7719", "String 39 Voltage", "V"),
    ("7720", "String 39 Current", "A"),
    ("7721", "String 40 Voltage", "V"),
    ("7722", "String 40 Current", "A"),
    ("11", "PV1 Power", "W"),
    ("12", "PV2 Power", "W"),
    ("13", "PV3 Power", "W"),
    ("59", "PV4 Power", "W"),
    ("60", "PV5 Power", "W"),
    ("61", "PV6 Power", "W"),
    ("62", "PV7 Power", "W"),
    ("63", "PV8 Power", "W"),
    ("64", "PV9 Power", "W"),
    ("65", "PV10 Power", "W"),
    ("3", "Total On-grid Running Time", "h"),
    ("29", "Operating Status", ""),
    # --- Plant (common-plant-measuring-points) ---
    ("83022", "Daily Yield of Plant", "Wh"),
    ("83024", "Plant Total Yield", "Wh"),
    ("83033", "Plant Power", "W"),
    ("83019", "Plant Power / Installed Power", ""),
    ("83006", "Meter Daily Yield", "Wh"),
    ("83020", "Meter Total Yield", "Wh"),
    ("83011", "Meter E-daily Consumption", "Wh"),
    ("83021", "Accumulative Power Consumption by Meter", "Wh"),
    ("83032", "Meter AC Power", "W"),
    ("83002", "Inverter AC Power", "W"),
    ("83004", "Inverter Total Yield", "Wh"),
    ("83009", "Inverter Daily Yield", "Wh"),
    ("83012", "P-radiation-H", "W/m²"),
    ("83013", "Daily Irradiation", "Wh/m²"),
    ("83023", "Plant PR", ""),
    ("83025", "Plant Equivalent Hours", "h"),
    ("83005", "Daily Equivalent Hours", "h"),
    ("83007", "Meter PR", ""),
    ("83018", "Daily Yield (Theoretical)", "Wh"),
    ("83001", "Inverter AC Power Normalization", "W/Wp"),
    ("83008", "Daily Equivalent Hours of Inverter", "h"),
    ("83010", "Inverter PR", ""),
    ("83016", "Plant Ambient Temperature", "°C"),
    ("83017", "Plant Module Temperature", "°C"),
    ("83046", "PCS Total Active Power", "W"),
    ("83052", "Load Power", "W"),
    ("83067", "Total Active Power of PV", "W"),
    ("83097", "Daily Direct Energy Consumption", "Wh"),
    ("83100", "Total Direct Energy Consumption", "Wh"),
    ("83102", "Energy Purchased Today", "Wh"),
    ("83105", "Total Purchased Energy", "Wh"),
    ("83106", "Load Power (2)", "W"),
    ("83118", "Daily Load Consumption", "Wh"),
    ("83124", "Total Load Consumption", "Wh"),
    ("83119", "Daily Feed-in Energy (PV)", "Wh"),
    # User-cloud getPsDetail / household report virtual total feed-in (#281).
    # Same quantity as open-API 83075; app path surfaces it as p83123_map.
    ("83123", "Total Feed-in Energy (PV)", "Wh"),
    ("83072", "Feed-in Energy Today", "Wh"),
    ("83075", "Feed-in Energy Total", "Wh"),
    # Nameplate PV capacity in watt-peak (surfaced by the user-account getPsDetail, #269).
    ("83202", "Nominal Power", "Wp"),
    ("83252", "Battery Level (SOC)", ""),
    ("83129", "Battery SOC", ""),
    ("83232", "Total field SOC", ""),
    ("83233", "Total field maximum rechargeable power", "W"),
    ("83234", "Total field maximum dischargeable power", "W"),
    ("83235", "Total field chargeable energy", "Wh"),
    ("83236", "Total field dischargeable energy", "Wh"),
    ("83237", "Total field energy storage maximum reactive power", "W"),
    ("83238", "Total field energy storage active power", "W"),
    ("83239", "Total field reactive power", "var"),
    ("83240", "Total field power factor", ""),
    ("83241", "Total field charge capacity", "Wh"),
    ("83242", "Total field discharge capacity", "Wh"),
    ("83243", "Daily field charge capacity", "Wh"),
    ("83244", "Daily field discharge capacity", "Wh"),
    ("83548", "Total Number of Charge/Discharge", ""),
    ("83549", "Grid Active Power", "W"),
    ("83419", "Daily Highest Inverter Power / Installed Capacity", ""),
    ("83317", "Power Forecast", "W"),
    ("83318", "Planned ES Charging/Discharging Power", "W"),
    ("83319", "Planned ES SOC", ""),
    ("83320", "Planned Charging Energy", "Wh"),
    ("83321", "Planned Discharging Energy", "Wh"),
    ("83322", "ESS Daily Charge (EMS)", "Wh"),
    ("83323", "ESS Daily Discharge (EMS)", "Wh"),
    ("83324", "Energy Storage Cumulative Charge", "Wh"),
    ("83325", "Cumulative Discharge", "Wh"),
    ("83326", "Energy Storage Active Power (EMS)", "W"),
    ("83327", "Energy Storage Remaining Charge", "Wh"),
    ("83328", "Grid Active Power (EMS)", "W"),
    ("83329", "PV Active Power (EMS)", "W"),
    ("83330", "Load Active Power (EMS)", "W"),
    ("83331", "Daily PV Yield (EMS)", "Wh"),
    ("83332", "Total PV Yield", "Wh"),
    ("83334", "Energy Storage SOC (EMS)", ""),
    ("83743", "Daily Yield Loss Due to Load Shedding", "Wh"),
    # --- Combiner box (common-combiner-box-measuring-points) ---
    ("1005", "Total DC Current", "A"),
    ("1001", "DC Bus Voltage", "V"),
    ("1006", "Total DC Power", "W"),
    ("1002", "Interior Temperature", "°C"),
    ("1009", "Ipv-1", "A"),
    ("1010", "Ipv-2", "A"),
    ("1011", "Ipv-3", "A"),
    ("1012", "Ipv-4", "A"),
    ("1013", "Ipv-5", "A"),
    ("1014", "Ipv-6", "A"),
    ("1015", "Ipv-7", "A"),
    ("1016", "Ipv-8", "A"),
    ("1017", "Ipv-9", "A"),
    ("1018", "Ipv-10", "A"),
    ("1019", "Ipv-11", "A"),
    ("1020", "Ipv-12", "A"),
    ("1021", "Ipv-13", "A"),
    ("1022", "Ipv-14", "A"),
    ("1023", "Ipv-15", "A"),
    ("1024", "Ipv-16", "A"),
    ("1025", "Ipv-17", "A"),
    ("1026", "Ipv-18", "A"),
    ("1027", "Ipv-19", "A"),
    ("1028", "Ipv-20", "A"),
    ("1029", "Ipv-21", "A"),
    ("1030", "Ipv-22", "A"),
    ("1031", "Ipv-23", "A"),
    ("1032", "Ipv-24", "A"),
    # --- PCS device (common-pcs-device-measuring-points) ---
    ("44010", "Overall Total Active Power", "W"),
    ("44011", "Overall Total Reactive Power", "var"),
    ("44012", "Overall Power Factor", ""),
    ("44025", "Work Mode", ""),
    ("44029", "Overall Grid Frequency", "Hz"),
    ("44231", "Running Status", ""),
    ("44244", "Internal Air Temperature", "°C"),
    ("44803", "Device S/N", ""),
    ("44823", "PCS-DSP Version Number", ""),
    ("44824", "PCS-CPLD Version Number", ""),
    # --- CMU device (common-cmu-device-measuring-points) ---
    ("59002", "Total Voltage", ""),
    ("59003", "Total Current", ""),
    ("59004", "SOC", ""),
    ("59006", "Rack Capacity", ""),
    ("59008", "Highest Cell Voltage", "mV"),
    ("59010", "Lowest Cell Voltage", "mV"),
    ("59012", "Highest Cell Temperature", "°C"),
    ("59014", "Min Cell Temperature", "°C"),
    ("59403", "Software Version", ""),
    # --- BSC device (common-bsc-device-measuring-points); shared cell IDs above ---
    ("59064", "Max Cell Voltage Position (#BMU~#Cell)", ""),
    ("59065", "Min Cell Voltage Position (#BMU~#Cell)", ""),
    ("59066", "Max Cell Temperature Position (#BMU~#Cell)", ""),
    ("59067", "Min Cell Temperature Position (#BMU~#Cell)", ""),
    # --- LC device (common-lc-device-measuring-points) ---
    ("59502", "Software Version", ""),
    ("59535", "Total Charge", "Wh"),
    ("59536", "Total Discharge", "Wh"),
    ("59541", "Total Active Power", "W"),
    ("59542", "Total Reactive Power", "var"),
    ("59546", "Daily Charge", "Wh"),
    ("59547", "Daily Discharge", "Wh"),
    ("59551", "Working Mode", ""),
    ("59552", "Working Status", ""),
    ("59705", "Device S/N", ""),
    # --- Microinverter (common-microinverter-measuring-points) ---
    ("51301", "Running Status", ""),
    ("51302", "Total Yield", "Wh"),
    ("51303", "Total Active Power", "W"),
    ("51304", "Total Reactive Power", "var"),
    ("51305", "Total DC Power", "W"),
    ("51306", "Total Apparent Power", "VA"),
    ("51307", "Total Power Factor", ""),
    ("51308", "Grid Frequency", "Hz"),
    ("51309", "AC Voltage", "V"),
    ("51312", "AC Current", "A"),
    ("51315", "PV1 Voltage", "V"),
    ("51316", "PV1 Current", "A"),
    ("51317", "PV2 Voltage", "V"),
    ("51318", "PV2 Current", "A"),
    ("51319", "PV3 Voltage", "V"),
    ("51320", "PV3 Current", "A"),
    ("51321", "PV4 Voltage", "V"),
    ("51322", "PV4 Current", "A"),
    ("51323", "PV5 Voltage", "V"),
    ("51324", "PV5 Current", "A"),
    ("51325", "PV6 Voltage", "V"),
    ("51326", "PV6 Current", "A"),
    ("51333", "PV1 Power", "W"),
    ("51334", "PV2 Power", "W"),
    ("51335", "PV3 Power", "W"),
    ("51336", "PV4 Power", "W"),
    ("51337", "PV5 Power", "W"),
    ("51338", "PV6 Power", "W"),
    ("51339", "PV1 Total Yield", "Wh"),
    ("51340", "PV2 Total Yield", "Wh"),
    ("51341", "PV3 Total Yield", "Wh"),
    ("51342", "PV4 Total Yield", "Wh"),
    ("51343", "PV5 Total Yield", "Wh"),
    ("51344", "PV6 Total Yield", "Wh"),
    ("51346", "Yield Today", "Wh"),
    ("51347", "PV1 Yield Today", "Wh"),
    ("51348", "PV2 Yield Today", "Wh"),
    ("51349", "PV3 Yield Today", "Wh"),
    ("51350", "PV4 Yield Today", "Wh"),
    ("51351", "PV5 Yield Today", "Wh"),
    ("51352", "PV6 Yield Today", "Wh"),
    # --- Environment monitoring (common-environment-monitoring-device-measuring-points) ---
    ("2003", "Transient Horizontal Irradiation", "W/m²"),
    ("2001", "Daily Horizontal Irradiation", "Wh/m²"),
    ("2002", "Total Horizontal Irradiation", "Wh/m²"),
    ("2007", "Slope Transient Irradiation", "W/m²"),
    ("2005", "Slope Daily Irradiation", "Wh/m²"),
    ("2006", "Total Slope Irradiation", "Wh/m²"),
    ("2009", "Ambient Temperature", "°C"),
    ("2010", "Temp. (PV module)", "°C"),
    ("2016", "Wind Speed", "m/s"),
    ("2011", "Wind Speed Scale", ""),
    ("2012", "Wind Angle", "°"),
    ("2014", "Atmospheric Pressure", "hPa"),
    ("2015", "Ambient Humidity", "%RH"),
    ("2022", "Rainfall", "mm"),
    ("2026", "Precipitation", "mm"),
    ("2100", "Temperature 1 (Backplane Temperature)", "°C"),
    ("2101", "Temperature 2", "°C"),
    ("2102", "Temperature 3", "°C"),
    ("2103", "Temperature 4", "°C"),
    ("2104", "Temperature 5", "°C"),
    ("2105", "Dew Point", ""),
    ("2106", "Soil Moisture 1", ""),
    ("2107", "Soil Moisture 2", ""),
    ("2108", "Soil Moisture 3", ""),
    ("2109", "CO₂", ""),
    ("2110", "Evaporation", ""),
    ("2111", "Instantaneous Value of Total Radiation 1", ""),
    ("2112", "Instantaneous Value of Scattering Radiation", ""),
    ("2113", "Instantaneous Value of Direct Radiation", ""),
    ("2114", "Instantaneous Value of Total Radiation 2", ""),
    ("2115", "Instantaneous Value of Net Radiation", ""),
    ("2116", "Instantaneous Value of Photosynthetic Radiation", ""),
    ("2117", "Instantaneous Value of Ultraviolet Radiation", ""),
    ("2118", "Instantaneous Value of Wind Direction", ""),
    ("2119", "Instantaneous Value of Wind Speed", ""),
    ("2120", "2-Minute Wind Speed", ""),
    ("2121", "10-Minute Wind Speed", ""),
    ("2122", "Cumulative Value of Rainfall Time Interval", ""),
    ("2123", "Cumulative Value of Sunshine Time Interval", ""),
    ("2124", "Cumulative Value of Total Radiation 1 Time Interval", ""),
    ("2125", "Cumulative Value of Scattering Radiation Time Interval", ""),
    ("2126", "Cumulative Value of Direct Radiation Time Interval", ""),
    ("2127", "Cumulative Value of Total Radiation 2 Time Interval", ""),
    ("2128", "Cumulative Value of Net Radiation Time Interval", ""),
    ("2129", "Cumulative Value of Photosynthetic Radiation Time Interval", ""),
    ("2130", "Cumulative Value of Ultraviolet Radiation Time Interval", ""),
    ("2131", "Daily Accumulation of Rainfall", ""),
    ("2132", "Daily Accumulation of Sunshine", ""),
    ("2133", "Daily Cumulative Value of Total Radiation 1", ""),
    ("2134", "Daily Cumulative Value of Scattering Radiation", ""),
    ("2135", "Daily Cumulative Value of Direct Radiation", ""),
    ("2136", "Daily Cumulative Value of Total Radiation 2", ""),
    ("2137", "Daily Cumulative Value of Net Radiation", ""),
    ("2138", "Daily Cumulative Value of Photosynthetic Radiation", ""),
    ("2139", "Daily Cumulative Value of Ultraviolet Radiation", ""),
    # --- Communications device (common-communications-device-measuring-points) ---
    ("10555", "AI Voltage Signal 1", "V"),
    ("10575", "AI Current Signal 1", "mA"),
    ("10557", "AI Voltage Signal 2", "V"),
    ("10576", "AI Current Signal 2", "mA"),
    ("10559", "AI Voltage Signal 3", "V"),
    ("10577", "AI Current Signal 3", "mA"),
    ("10561", "AI Voltage Signal 4", "V"),
    ("10578", "AI Current Signal 4", "mA"),
    ("10563", "PT Signal 1", "°C"),
    ("10565", "PT Signal 2", "°C"),
    ("10567", "DO Signal 1", ""),
    ("10569", "DO Signal 2", ""),
    ("10571", "DO Signal 3", ""),
    ("10573", "DO Signal 4", ""),
    ("10026", "Total Power", "W"),
    ("10028", "Total Yield", "Wh"),
    ("10046", "Total Reactive Power", "var"),
    ("10510", "Mobile Network Signal Strength", ""),
    ("10511", "WLAN Signal Strength", ""),
    ("10587", "Total Active Power", "W"),
    # --- Communications module (common-communications-module-measuring-points) ---
    ("23001", "Wireless Signal Strength", ""),
    ("23014", "WLAN Signal Strength", ""),
    ("23008", "Card ID", ""),
    # --- iHomeManage (common-ihomemanage-measuring-points) ---
    ("88016", "Channel 1 Total Active Power", "W"),
    ("88017", "Channel 1 Phase A Active Power", "W"),
    ("88018", "Channel 1 Phase B Active Power", "W"),
    ("88019", "Channel 1 Phase C Active Power", "W"),
    ("88034", "Channel 1 Total Purchased Energy", "Wh"),
    ("88035", "Channel 1 Total Feed-in Energy", "Wh"),
]

# --- Friendly names for known codes (built-in default + recommended user codes) ---
CODE_ALIASES: dict[str, str] = {
    # Built-in plant/battery default codes (from pysolarcloud).
    "total_field_energy_storage_active_power": "Battery Power",
    "total_field_energy_storage_maximum_reactive_power": "Battery Max Reactive Power",
    "total_field_chargeable_energy": "Battery Chargeable Energy",
    "total_field_dischargeable_energy": "Battery Dischargeable Energy",
    "total_field_maximum_rechargeable_power": "Battery Max Charge Power",
    "total_field_maximum_dischargeable_power": "Battery Max Discharge Power",
    "total_field_power_factor": "Battery Power Factor",
    "total_field_reactive_power": "Battery Reactive Power",
    "total_field_soc": "Battery State of Charge (Field)",
    "daily_field_charge_capacity": "Battery Daily Charge Capacity",
    "daily_field_discharge_capacity": "Battery Daily Discharge Capacity",
    "total_field_charge_capacity": "Battery Total Charge Capacity",
    "total_field_discharge_capacity": "Battery Total Discharge Capacity",
    "total_number_of_charge_discharge": "Battery Charge/Discharge Cycles",
    "energy_storage_active_power_ems": "EMS Battery Power",
    "energy_storage_soc_ems": "EMS Battery SOC",
    "battery_level_soc": "Battery State of Charge",
    "meter_pr": "Meter Performance Ratio",
    "plant_pr": "Plant Performance Ratio",
    "inverter_pr": "Inverter Performance Ratio",
    "power_fraction": "Plant Power / Installed Power",
    # Recommended user-supplied codes (docs/SENSORS.md).
    "battery_charge_power": "Battery Charge Power",
    "battery_discharge_power": "Battery Discharge Power",
    "ev_charger_power": "EV Charger Power",
    "ev_charger_energy": "EV Charger Energy",
    "battery_level": "Battery Level",
    "battery_soh": "Battery Health (SOH)",
    "battery_voltage": "Battery Voltage",
    "battery_current": "Battery Current",
    "battery_temperature": "Battery Temperature",
    "battery_total_charge_energy": "Battery Total Charge Energy",
    "battery_total_discharge_energy": "Battery Total Discharge Energy",
    "ev_charger_max_power": "EV Charger Max Power",
    "ev_charger_status": "EV Charger Status",
    "meter_forward_active_energy": "Meter Forward Active Energy",
    "meter_reverse_active_energy": "Meter Reverse Active Energy",
    "meter_daily_forward_active_energy": "Meter Daily Forward Active Energy",
    "meter_daily_reverse_active_energy": "Meter Daily Reverse Active Energy",
    "meter_active_power": "Meter Active Power",
    "meter_power_factor": "Meter Power Factor",
    "meter_apparent_power": "Meter Apparent Power",
    "meter_frequency": "Meter Frequency",
    # Energy-storage-inverter recommended codes (docs/SENSORS.md).
    "battery_soc": "Battery Level (SOC)",
    "load_power": "Load Power",
    "feed_in_power": "Feed-in Power",
    "purchased_power": "Purchased Power",
    "inverter_operating_status": "Inverter Operating Status",
    # EMS recommended codes.
    "ems_storage_power": "EMS Storage Power",
    "ems_storage_soc": "EMS Storage SOC",
    "ems_grid_power": "EMS Grid Power",
    "ems_pv_power": "EMS PV Power",
    "ems_active_load": "EMS Active Load",
    "ems_total_charge": "EMS Total Charge",
    "ems_total_discharge": "EMS Total Discharge",
    # Microinverter recommended codes.
    "micro_active_power": "Microinverter Active Power",
    "micro_total_yield": "Microinverter Total Yield",
    "micro_yield_today": "Microinverter Yield Today",
    "micro_power_factor": "Microinverter Power Factor",
    "micro_running_status": "Microinverter Running Status",
    # Local Modbus enum sensors (#322): raw register-code sensors are decoded
    # to display strings via ENUM_MAPS. These aliases give them clear names
    # instead of the fallback title-cased "Running State Raw" / "Device Type Code".
    "running_state_raw": "Inverter State",
    "device_type_code": "Device Model",
    # Per-device diagnostic codes whose acronyms/initialisms the generic
    # title-caser would mangle ("Mppt1", "Wlan", "Afci", "Dc", "Id").
    "mppt1_voltage": "MPPT1 Voltage",
    "mppt1_current": "MPPT1 Current",
    "mppt2_voltage": "MPPT2 Voltage",
    "mppt2_current": "MPPT2 Current",
    "mppt3_voltage": "MPPT3 Voltage",
    "mppt3_current": "MPPT3 Current",
    "total_dc_power": "Total DC Power",
    "negative_voltage_to_ground": "Negative Voltage to Ground",
    "afci_fault_count": "AFCI Fault Count",
    "wlan_signal_strength": "WLAN Signal Strength",
    "battery_dc_contactor_status": "Battery DC Contactor Status",
    "battery_fault_module_id": "Battery Fault Module ID",
    # Named fields from getPsDetail (cloud_user transport, #292).
    "current_power": "Current Power",
    "today_energy": "Energy Today",
    "total_energy": "Total Energy",
    "month_energy": "Energy This Month",
    "co2_reduce_total": "CO₂ Reduction Total",
    "today_income": "Income Today",
    "total_income": "Total Income",
}
