#!/usr/bin/env python3
"""Generate ``docs/SUPPORTED_MODELS.md`` from :data:`MODEL_SPECS` (#437).

``MODEL_SPECS`` is the source of truth for per-model behaviour, but it is Python, so
"will my inverter work, and what will the sliders do?" could only be answered by reading
the catalog. A hand-written table would drift the first time a spec changed, and a stale
compatibility table is worse than none, so the page is generated and ``tests`` fails when
the committed copy is out of date.

Usage (from the repository root)::

    python scripts/generate_supported_models.py [output_path]
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from custom_components.sungrow.model_specs import MODEL_SPECS  # noqa: E402

DEFAULT_OUTPUT = REPO_ROOT / "docs" / "SUPPORTED_MODELS.md"

# Model-code prefix -> the family wording used by docs/model-support.md.
FAMILY_LABELS: dict[str, str] = {
    "SG": "PV string inverter",
    "SH": "Hybrid / storage",
    "MG": "Hybrid / storage",
}

EMPTY = "—"
COLUMNS = (
    "Model",
    "Family",
    "Phases",
    "MPPT",
    "Strings",
    "AC nameplate",
    "Battery charge",
    "Battery discharge",
    "Source",
)


def _watts(value: int | None) -> str:
    """Format a watt rating, or an em dash when the datasheet field doesn't apply."""
    return f"{value:,} W" if value is not None else EMPTY


def render() -> str:
    """Return the generated page for whatever :data:`MODEL_SPECS` currently holds."""
    lines = [
        "---",
        "icon: lucide/table-2",
        "---",
        "",
        "# Supported models",
        "",
        "<!-- Generated by scripts/generate_supported_models.py from MODEL_SPECS. Do not edit by hand. -->",
        "",
        "One row per model in the integration's datasheet catalog. The catalog decides the",
        "dispatch slider ceilings (charge/discharge power, export limiting) and the per-family",
        "point requests; see the [Model support matrix](model-support.md) for what each family",
        "reports, and how a model the resolver doesn't recognise still works with conservative",
        "defaults.",
        "",
        "| " + " | ".join(COLUMNS) + " |",
        "|" + "|".join(["---"] * len(COLUMNS)) + "|",
    ]
    for model, spec in MODEL_SPECS.items():
        prefix = model[:2].upper()
        lines.append(
            "| `{model}` | {family} | {phases} | {mppt} | {strings} | {ac} | {charge} | {discharge} | {source} |".format(
                model=model,
                family=FAMILY_LABELS.get(prefix, prefix),
                phases=spec.phases,
                mppt=spec.mppt_count,
                strings=spec.string_count,
                ac=_watts(spec.max_ac_output_power),
                charge=_watts(spec.max_charge_power),
                discharge=_watts(spec.max_discharge_power),
                source="Estimate" if spec.unverified else "Datasheet",
            )
        )
    lines += [
        "",
        f"{len(MODEL_SPECS)} models.",
        "",
        "**Source** is `Datasheet` when the row's values were cross-referenced against a Sungrow",
        "datasheet, and `Estimate` when they are a family estimate (the MG hybrids). The",
        "charge/discharge sliders ignore estimated battery values and fall back to the AC",
        "nameplate, so a slider can legitimately stop below the numbers above.",
        "",
        "Battery columns show an em dash on PV-only models, which have no battery to charge.",
        "",
        "## Adding a model",
        "",
        "The catalog is intentionally sparse — only the residential lineup is listed, and only",
        "the fields the integration consumes. To add a model, add a row to `MODEL_SPECS` in",
        "`custom_components/sungrow/model_specs.py` and run:",
        "",
        "```bash",
        "python scripts/generate_supported_models.py",
        "```",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    """Write the generated page, defaulting to the committed docs path."""
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT
    output.write_text(render(), encoding="utf-8")
    print(f"Wrote {output.relative_to(REPO_ROOT) if output.is_relative_to(REPO_ROOT) else output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
